spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/digital_twin_agriculture
spring.datasource.username=postgres
spring.datasource.password=ashi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
