spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-late-paper-av4s8mig-pooler.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XqUSTkcz89sw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081